apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: iwc
resources:
    - ../base
patchesStrategicMerge:
    - ing.patch.yml
    - dpl.patch.yml
nameSuffix: -staging
images:
    - name: ghcr.io/iwannacommunity/delfruit-backend
      newTag: beta
commonLabels:
    env: staging